//! election — forge lab 03 (byzantine).
//!
//! Leader election over a hostile wire. You write the node's decision
//! logic; this file is the network, the clock, and the judge. Five nodes,
//! messages that can be lost, partitions that cut the wire, and one rule
//! above all: **at most one leader per term. Ever.**
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/raft.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! What you implement (Raft, election layer only — logs come in lab 04):
//!   * `on_timeout()` — an election timer fired. Become candidate, bump
//!     term, vote for yourself, broadcast RequestVote.
//!   * `on_msg(RequestVote)` — grant if: their term ≥ yours AND you
//!     haven't voted this term. Otherwise refuse. A higher term updates
//!     yours (and steps you down).
//!   * `on_msg(RequestVoteReply)` — count grants; a majority makes you
//!     leader. (The harness counts your role via `role()`.)
//!
//! Messages the harness may inject at any time: loss, delay, duplication,
//! and partitions. Your logic must be safe under all of them.

mod raft;

use raft::{Msg, Raft, Role};
use kslab::{Check, Report};

pub const N: usize = 5;

/* ------------------------- the hostile wire ------------------------- */

#[derive(Clone)]
struct Envelope {
    from: usize,
    to: usize,
    msg: Msg,
    deliver_at: u32,
}

struct Net {
    tick: u32,
    in_flight: Vec<Envelope>,
    /// when Some((a, b)), the wire drops all traffic between groups a and b
    partition: Option<(Vec<usize>, Vec<usize>)>,
    loss_pct: u32,
    rng: u64,
}

impl Net {
    fn new(loss_pct: u32) -> Self {
        Net { tick: 0, in_flight: Vec::new(), partition: None, loss_pct, rng: 0xE1EC }
    }
    fn rand(&mut self) -> u64 {
        let mut x = self.rng;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.rng = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn deliverable(&self, from: usize, to: usize) -> bool {
        if let Some((a, b)) = &self.partition {
            let ina = |x: usize| a.contains(&x);
            let inb = |x: usize| b.contains(&x);
            if (ina(from) && inb(to)) || (inb(from) && ina(to)) {
                return false;
            }
        }
        true
    }
}

/* The driver: timeouts tick the nodes; deliveries pass through the knife. */
/* The driver: per-node silence counters ARE the election timer. A leader
   heartbeats every HB_TICKS; any AppendEntries from a current/newer term
   resets the receiver's silence. Timeout with no contact → on_timeout. */
const HB_TICKS: u32 = 6;

fn drive(net: &mut Net, nodes: &mut [Raft], ticks: u32) {
    let mut silent: Vec<u32> = vec![0; nodes.len()];
    // per-node deterministic streams → randomized-timeout behavior without
    // the timing lottery of real randomness
    let mut streams: Vec<u64> = (0..nodes.len()).map(|i| 0x9E37_5AFE + i as u64 * 0x1_2345_6789).collect();
    for _ in 0..ticks {
        net.tick += 1;
        // leaders heartbeat
        if net.tick % HB_TICKS == 0 {
            for (i, node) in nodes.iter().enumerate() {
                if node.role() == Role::Leader {
                    queue_broadcast(net, i, vec![Msg::AppendEntries {
                        term: node.term(),
                        leader: i as u32,
                        prev_log_index: 0,
                        prev_log_term: 0,
                        entries: vec![],
                        leader_commit: 0,
                    }]);
                }
            }
        }
        // election timers
        for (i, node) in nodes.iter_mut().enumerate() {
            silent[i] += 1;
            let mut x = streams[i];
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            streams[i] = x;
            let timeout = 12 + (x.wrapping_mul(0x2545_F491_4F6C_DD1D) % 14) as u32;
            if silent[i] >= timeout {
                silent[i] = 0;
                let out = node.on_timeout();
                queue_broadcast(net, i, out);
            }
        }
        // deliveries
        let arrivals: Vec<Envelope> = std::mem::take(&mut net.in_flight);
        let mut still = Vec::new();
        for env in arrivals {
            if env.deliver_at > net.tick {
                still.push(env);
                continue;
            }
            if !net.deliverable(env.from, env.to) {
                continue;
            }
            let resets = matches!(&env.msg, Msg::AppendEntries { term, .. } if *term >= nodes[env.to].term());
            let out = nodes[env.to].on_msg(env.from as u32, env.msg);
            if resets {
                silent[env.to] = 0;
            }
            queue_broadcast(net, env.to, out);
        }
        net.in_flight.append(&mut still);
    }
}

fn queue_broadcast(net: &mut Net, from: usize, msgs: Vec<Msg>) {
    for msg in msgs {
        for to in 0..N {
            if to == from {
                continue;
            }
            if net.rand() % 100 < net.loss_pct as u64 {
                continue;
            }
            let delay = (net.rand() % 3) as u32;
            net.in_flight.push(Envelope { from, to, msg: msg.clone(), deliver_at: net.tick + delay });
        }
    }
}

fn leaders(nodes: &[Raft]) -> Vec<(usize, u64)> {
    nodes
        .iter()
        .enumerate()
        .filter(|(_, n)| n.role() == Role::Leader)
        .map(|(i, n)| (i, n.term()))
        .collect()
}

/* ------------------------------ checks ------------------------------ */

/// 1. clean_election: a quiet wire elects exactly one leader.
pub fn check_clean_election() -> Check {
    const ID: &str = "clean_election";
    const LABEL: &str = "one leader emerges on a quiet wire";
    let mut net = Net::new(0);
    let mut nodes: Vec<Raft> = (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect();
    drive(&mut net, &mut nodes, 60);
    let ls = leaders(&nodes);
    if ls.len() != 1 {
        return Check::fail(ID, LABEL, format!("{} leaders after 60 quiet ticks: {:?}", ls.len(), ls));
    }
    Check::pass(ID, LABEL, format!("node {} leads term {}", ls[0].0, ls[0].1))
}

/// 2. one_per_term: under loss, every term has at most one leader.
pub fn check_one_per_term() -> Check {
    const ID: &str = "one_per_term";
    const LABEL: &str = "at most one leader per term, under loss";
    let mut net = Net::new(25);
    let mut nodes: Vec<Raft> = (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect();
    let mut seen: std::collections::HashMap<u64, usize> = Default::default();
    for round in 0..40 {
        drive(&mut net, &mut nodes, 12);
        for (i, term) in leaders(&nodes) {
            if let Some(prev) = seen.insert(term, i) {
                if prev != i {
                    return Check::fail(ID, LABEL, format!("term {term} has two leaders: n{prev} and n{i} (round {round})"));
                }
            }
        }
    }
    Check::pass(ID, LABEL, "480 ticks of lossy churn: never two leaders in one term")
}

/// 3. minority_refuses: a 2|3 partition — the 2-side must not elect.
pub fn check_minority_refuses() -> Check {
    const ID: &str = "minority_refuses";
    const LABEL: &str = "the minority side of a partition elects no one";
    let mut net = Net::new(0);
    net.partition = Some((vec![0, 1], vec![2, 3, 4]));
    let mut nodes: Vec<Raft> = (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect();
    drive(&mut net, &mut nodes, 80);
    let minority_leaders = leaders(&nodes).into_iter().filter(|(i, _)| *i < 2).count();
    if minority_leaders > 0 {
        return Check::fail(ID, LABEL, "a 2-node minority elected a leader — split brain!");
    }
    let majority_leaders = leaders(&nodes).into_iter().filter(|(i, _)| *i >= 2).count();
    if majority_leaders != 1 {
        return Check::fail(ID, LABEL, format!("the 3-node majority should elect exactly one leader, got {majority_leaders}"));
    }
    Check::pass(ID, LABEL, "minority refused; majority elected exactly one")
}

/// 4. term_fencing: a healed stale leader steps down on seeing a newer term.
pub fn check_term_fencing() -> Check {
    const ID: &str = "term_fencing";
    const LABEL: &str = "stale leaders step down after healing";
    let mut net = Net::new(0);
    let mut nodes: Vec<Raft> = (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect();
    drive(&mut net, &mut nodes, 40); // elect someone (likely n0)
    let first = leaders(&nodes).first().copied();
    let Some((first_id, first_term)) = first else {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    };
    // partition the leader alone; it cannot win a new election, others bump terms
    net.partition = Some((vec![first_id], (0..N).filter(|&i| i != first_id).collect()));
    drive(&mut net, &mut nodes, 60);
    // heal
    net.partition = None;
    drive(&mut net, &mut nodes, 40);
    let now = leaders(&nodes);
    if now.iter().any(|(i, t)| *i == first_id && *t == first_term) {
        return Check::fail(ID, LABEL, format!("n{first_id} still claims leadership of dead term {first_term} after healing"));
    }
    Check::pass(ID, LABEL, format!("term {first_term} leader fenced; current term {}", now.first().map(|x| x.1).unwrap_or(0)))
}

/// 5. split_votes_resolve: two candidates at once — eventually exactly one leader.
pub fn check_split_votes() -> Check {
    const ID: &str = "split_votes";
    const LABEL: &str = "split votes resolve to one leader";
    let mut net = Net::new(10);
    let mut nodes: Vec<Raft> = (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect();
    // force near-simultaneous timeouts (same phase)
    drive(&mut net, &mut nodes, 300);
    let ls = leaders(&nodes);
    if ls.len() != 1 {
        return Check::fail(ID, LABEL, format!("{} leaders after 300 ticks of tight timeouts", ls.len()));
    }
    Check::pass(ID, LABEL, format!("one leader after contention (n{}, term {})", ls[0].0, ls[0].1))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_clean_election(),
        check_one_per_term(),
        check_minority_refuses(),
        check_term_fencing(),
        check_split_votes(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "election", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
