//! raft-log — forge lab 04 (byzantine).
//!
//! The log, not just the leader. Bring your lab-03 election code forward,
//! then add the machinery that makes leadership mean something: append,
//! match, commit. The harness proposes client writes; you keep them safe.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/raft.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! On top of lab 03's election layer, add:
//!   * `propose(cmd)` (leader only): append (term, cmd) to your log,
//!     broadcast AppendEntries with prev_log_index/term + leader_commit.
//!   * Followers: accept iff the log matches at (prev_log_index,
//!     prev_log_term); append new entries (truncating conflicts); reply
//!     AppendEntriesReply { success, match_index }; commit up to
//!     min(leader_commit, last_index).
//!   * Leaders: on successful replies, advance commit_index once a
//!     MAJORITY holds an entry from the CURRENT term, then keep telling
//!     followers via leader_commit.
//!
//! The judges: `commit_index()` and `log()` (committed prefix must be
//! identical on every live node, and committed entries never disappear).

mod raft;

use raft::{Msg, Raft, Role};
use kslab::{Check, Report};

pub const N: usize = 5;
const HB_TICKS: u32 = 6;

/* ------------------------- the hostile wire ------------------------- */

#[derive(Clone)]
struct Envelope {
    from: usize,
    to: usize,
    msg: Msg,
    deliver_at: u32,
}

struct Net {
    tick: u32,
    in_flight: Vec<Envelope>,
    partition: Option<(Vec<usize>, Vec<usize>)>,
    loss_pct: u32,
    rng: u64,
}

impl Net {
    fn new(loss_pct: u32) -> Self {
        Net { tick: 0, in_flight: Vec::new(), partition: None, loss_pct, rng: 0x10C6 }
    }
    fn rand(&mut self) -> u64 {
        let mut x = self.rng;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.rng = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn deliverable(&self, from: usize, to: usize) -> bool {
        if let Some((a, b)) = &self.partition {
            let ina = |x: usize| a.contains(&x);
            let inb = |x: usize| b.contains(&x);
            if (ina(from) && inb(to)) || (inb(from) && ina(to)) {
                return false;
            }
        }
        true
    }
}

fn queue_broadcast(net: &mut Net, from: usize, msgs: Vec<Msg>) {
    for msg in msgs {
        for to in 0..N {
            if to == from {
                continue;
            }
            if net.rand() % 100 < net.loss_pct as u64 {
                continue;
            }
            let delay = (net.rand() % 3) as u32;
            net.in_flight.push(Envelope { from, to, msg: msg.clone(), deliver_at: net.tick + delay });
        }
    }
}

struct Driver {
    net: Net,
    nodes: Vec<Raft>,
    silent: Vec<u32>,
    streams: Vec<u64>,
}

impl Driver {
    fn new(loss_pct: u32) -> Self {
        Driver {
            net: Net::new(loss_pct),
            nodes: (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect(),
            silent: vec![0; N],
            streams: (0..N).map(|i| 0x9E37_5AFE + i as u64 * 0x1_2345_6789).collect(),
        }
    }
    fn leader(&self) -> Option<usize> {
        self.nodes.iter().position(|n| n.role() == Role::Leader)
    }
    fn step(&mut self) {
        self.net.tick += 1;
        let t = self.net.tick;
        if t % HB_TICKS == 0 {
            for i in 0..N {
                if self.nodes[i].role() == Role::Leader {
                    let out = self.nodes[i].heartbeat();
                    queue_broadcast(&mut self.net, i, out);
                }
            }
        }
        for i in 0..N {
            // leaders don't run election timers — they're not waiting for a heartbeat
            if self.nodes[i].role() == Role::Leader {
                continue;
            }
            self.silent[i] += 1;
            let mut x = self.streams[i];
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            self.streams[i] = x;
            let timeout = 12 + (x.wrapping_mul(0x2545_F491_4F6C_DD1D) % 14) as u32;
            if self.silent[i] >= timeout {
                self.silent[i] = 0;
                let out = self.nodes[i].on_timeout();
                queue_broadcast(&mut self.net, i, out);
            }
        }
        let arrivals: Vec<Envelope> = std::mem::take(&mut self.net.in_flight);
        let mut still = Vec::new();
        for env in arrivals {
            if env.deliver_at > t {
                still.push(env);
                continue;
            }
            if !self.net.deliverable(env.from, env.to) {
                continue;
            }
            let resets = matches!(&env.msg, Msg::AppendEntries { term, .. } if *term >= self.nodes[env.to].term());
            let out = self.nodes[env.to].on_msg(env.from as u32, env.msg);
            if resets {
                self.silent[env.to] = 0;
            }
            queue_broadcast(&mut self.net, env.to, out);
        }
        self.net.in_flight.append(&mut still);
    }
    fn drive(&mut self, ticks: u32) {
        for _ in 0..ticks {
            self.step();
        }
    }
    fn propose(&mut self, cmd: &str) -> bool {
        let Some(l) = self.leader() else { return false };
        let out = self.nodes[l].propose(cmd.to_string());
        queue_broadcast(&mut self.net, l, out);
        true
    }
    fn committed_logs(&self) -> Vec<Vec<String>> {
        self.nodes.iter().map(|n| n.log().into_iter().take(n.commit_index() as usize).collect()).collect()
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. replicate_basic: one write commits on a majority and survives.
pub fn check_replicate_basic() -> Check {
    const ID: &str = "replicate_basic";
    const LABEL: &str = "a write replicates and commits on a majority";
    let mut d = Driver::new(0);
    d.drive(40); // elect
    if d.leader().is_none() {
        return Check::fail(ID, LABEL, "no leader after 40 quiet ticks");
    }
    if !d.propose("set x=1") {
        return Check::fail(ID, LABEL, "propose failed with a live leader");
    }
    d.drive(40);
    let logs = d.committed_logs();
    let committed = logs.iter().filter(|l| l.contains(&"set x=1".to_string())).count();
    if committed < 3 {
        return Check::fail(ID, LABEL, format!("write committed on {committed}/{N} nodes — need a majority"));
    }
    Check::pass(ID, LABEL, format!("committed on {committed}/{N} nodes"))
}

/// 2. majority_required: with only 2 of 5 reachable, NO commit may happen.
pub fn check_majority_required() -> Check {
    const ID: &str = "majority_required";
    const LABEL: &str = "no commit without a majority";
    let mut d = Driver::new(0);
    d.drive(40);
    let Some(leader) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    };
    // isolate the leader + one follower from the other three
    d.net.partition = Some((vec![leader, (leader + 1) % N], (0..N).filter(|i| *i != leader && *i != (leader + 1) % N).collect()));
    let committed_before = d.nodes[leader].commit_index();
    d.propose("set danger=1");
    d.drive(50);
    if d.nodes[leader].commit_index() > committed_before {
        return Check::fail(ID, LABEL, "a 2-node island committed a write — that is the split-brain bug, live");
    }
    Check::pass(ID, LABEL, "the island held the write uncommitted — exactly right")
}

/// 3. heal_and_catchup: after healing, the island's nodes converge to the
///    majority's log (stale entries overwritten, not kept).
pub fn check_heal_and_catchup() -> Check {
    const ID: &str = "heal_and_catchup";
    const LABEL: &str = "post-heal convergence to one log";
    let mut d = Driver::new(0);
    d.drive(40);
    let Some(leader) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    };
    d.propose("set a=1");
    d.drive(30);
    // split off two followers, write through the majority
    let others: Vec<usize> = (0..N).filter(|i| *i != leader).collect();
    d.net.partition = Some((others[..2].to_vec(), others[2..].to_vec()));
    d.propose("set b=2");
    d.drive(40);
    // heal everything and give it time to converge
    d.net.partition = None;
    d.drive(60);
    let logs = d.committed_logs();
    let reference = &logs[leader];
    for (i, l) in logs.iter().enumerate() {
        if l != reference {
            return Check::fail(ID, LABEL, format!("node {i} committed log diverged after heal: {l:?} vs {reference:?}"));
        }
    }
    if !reference.contains(&"set b=2".to_string()) {
        return Check::fail(ID, LABEL, "the majority write was lost during the partition");
    }
    Check::pass(ID, LABEL, "all five nodes share one committed prefix")
}

/// 4. no_committed_loss: a committed entry survives a leader change.
pub fn check_no_committed_loss() -> Check {
    const ID: &str = "no_committed_loss";
    const LABEL: &str = "committed entries survive leader change";
    let mut d = Driver::new(0);
    d.drive(40);
    let Some(first) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    };
    d.propose("set precious=1");
    d.drive(40);
    if d.nodes[first].commit_index() == 0 {
        return Check::fail(ID, LABEL, "write never committed in phase 1");
    }
    // kill the leader's island: isolate it entirely, let the rest re-elect
    d.net.partition = Some((vec![first], (0..N).filter(|i| *i != first).collect()));
    d.drive(80);
    d.net.partition = None;
    d.drive(60);
    let still = d.committed_logs().iter().all(|l| l.contains(&"set precious=1".to_string()) || !l.contains(&"set precious=1".to_string()) && false);
    let survived = d.committed_logs().iter().any(|l| l.contains(&"set precious=1".to_string()));
    if !survived || !still {
        return Check::fail(ID, LABEL, "a committed entry vanished after the leader change");
    }
    Check::pass(ID, LABEL, "the committed write lived through the failover")
}

/// 5. storm: 30 writes under 20% loss — every node's committed prefix identical.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "30 writes under loss: one committed history on all nodes";
    let mut d = Driver::new(20);
    d.drive(50);
    for i in 0..30 {
        d.propose(&format!("set k{i}={i}"));
        d.drive(8);
    }
    d.drive(160);
    let logs = d.committed_logs();
    let reference = logs[0].clone();
    for (i, l) in logs.iter().enumerate() {
        if *l != reference {
            return Check::fail(ID, LABEL, format!("node {i} diverged: {l:?} vs {reference:?}"));
        }
    }
    if reference.len() < 15 {
        return Check::fail(ID, LABEL, format!("only {} entries committed — commits are stalling, not just losing the uncommitted tail", reference.len()));
    }
    Check::pass(ID, LABEL, format!("{} entries, identical on all five nodes", reference.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_replicate_basic(),
        check_majority_required(),
        check_heal_and_catchup(),
        check_no_committed_loss(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "raft-log", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
