//! kv-store — forge lab 02 (byzantine).
//!
//! A sequential key-value store behind an unreliable client network. One
//! node, no replication (that's lab 04+). The lesson: correct semantics
//! under retries — clients resend when the response is lost, and your
//! store must make that safe. Single-copy linearizability, by hand.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/store.rs       (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The ops: get / put / cas(expected, new) / delete. The hard parts:
//!   * cas is compare-and-swap: it applies only when the current value
//!     equals `expected` (missing counts as None). It is the primitive
//!     every safe retry protocol builds on.
//!   * Every response carries a monotonically increasing `version` —
//!     the count of mutations applied. Retries must not bump it twice.

mod store;

use store::Store;
use kslab::{Check, Report};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. basics: get/put/delete behave.
pub fn check_basics() -> Check {
    const ID: &str = "basics";
    const LABEL: &str = "get/put/delete semantics";
    let mut s = Store::new();
    if s.get("a") != None {
        return Check::fail(ID, LABEL, "get on missing key must be None");
    }
    s.put("a", "1");
    if s.get("a").as_deref() != Some("1") {
        return Check::fail(ID, LABEL, format!("get(a) = {:?}, want Some(\"1\")", s.get("a")));
    }
    s.put("a", "2");
    if s.get("a").as_deref() != Some("2") {
        return Check::fail(ID, LABEL, "put must overwrite");
    }
    s.delete("a");
    if s.get("a") != None {
        return Check::fail(ID, LABEL, "get after delete must be None");
    }
    Check::pass(ID, LABEL, "the happy path works")
}

/// 2. cas_semantics: compare-and-swap only applies on equality; missing
///    key compares as None.
pub fn check_cas_semantics() -> Check {
    const ID: &str = "cas_semantics";
    const LABEL: &str = "cas applies only on exact match";
    let mut s = Store::new();
    if !s.cas("k", None, "v1") {
        return Check::fail(ID, LABEL, "cas on missing key (expected None) should apply");
    }
    if s.cas("k", None, "v2") {
        return Check::fail(ID, LABEL, "cas with expected=None after a put must fail");
    }
    if !s.cas("k", Some("v1"), "v2") {
        return Check::fail(ID, LABEL, "cas with the right expected value must apply");
    }
    if s.get("k").as_deref() != Some("v2") {
        return Check::fail(ID, LABEL, "cas did not store the new value");
    }
    Check::pass(ID, LABEL, "equality gate works, including None")
}

/// 3. versions: every mutation bumps the version exactly once; reads and
///    failed cas don't move it.
pub fn check_versions() -> Check {
    const ID: &str = "versions";
    const LABEL: &str = "version counts mutations, once each";
    let mut s = Store::new();
    let v0 = s.version();
    s.put("a", "1");
    s.put("b", "2");
    s.get("a");
    s.cas("a", Some("wrong"), "x");
    let v1 = s.version();
    if v1 != v0 + 2 {
        return Check::fail(ID, LABEL, format!("version moved {v0} → {v1} for 2 mutations + 1 read + 1 failed cas — want +2"));
    }
    s.delete("a");
    if s.version() != v1 + 1 {
        return Check::fail(ID, LABEL, "delete is a mutation and must bump the version");
    }
    Check::pass(ID, LABEL, "one bump per mutation, nothing else")
}

/// 4. retry_safety: the same client op applied twice changes state once
///    (the lab-01 discipline at store level).
pub fn check_retry_safety() -> Check {
    const ID: &str = "retry_safety";
    const LABEL: &str = "an op retried after a lost response applies once";
    let mut s = Store::new();
    // client puts, response lost, client retries the same op
    s.put("counter", "1");
    let v1 = s.version();
    s.put("counter", "1"); // identical retry — same value, is it a new mutation?
    if s.get("counter").as_deref() != Some("1") {
        return Check::fail(ID, LABEL, "value changed under retry?");
    }
    // NOTE: a blind second put is indistinguishable from a new write — this
    // check just pins the honest behavior: version bumps, value correct.
    // (Lab 03+ adds request ids to make retries FREE.)
    if s.version() != v1 + 1 {
        return Check::fail(ID, LABEL, "an identical retried put still counts as a mutation — that's why cas exists");
    }
    Check::pass(ID, LABEL, "retry semantics pinned: identical writes are new writes (hence cas)")
}

/// 5. storm: 2000 mixed ops vs a model — every read matches the model's
///    last write, versions stay exact.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "2000 ops vs a reference model";
    let mut s = Store::new();
    let mut model: std::collections::HashMap<String, String> = Default::default();
    let mut rng = Rng(0x5EED);
    let mut mutations = 0usize;
    for i in 0..2000 {
        let key = format!("k{}", rng.below(32));
        match rng.below(100) {
            0..=39 => {
                let val = format!("v{i}");
                s.put(&key, &val);
                model.insert(key, val);
                mutations += 1;
            }
            40..=59 => {
                let expected = model.get(&key).cloned();
                let newval = format!("c{i}");
                let ok = s.cas(&key, expected.as_deref(), &newval);
                if ok {
                    model.insert(key, newval);
                    mutations += 1;
                } else if model.get(&key).map(String::as_str) == expected.as_deref() {
                    return Check::fail(ID, LABEL, format!("op {i}: cas({key}, {expected:?}) failed but the model value matches — false negative"));
                }
            }
            60..=79 => {
                s.delete(&key);
                model.remove(&key);
                mutations += 1;
            }
            _ => {
                let got = s.get(&key);
                let want = model.get(&key);
                if got.as_deref() != want.map(|x| x.as_str()) {
                    return Check::fail(ID, LABEL, format!("op {i}: get({key}) = {got:?}, model says {want:?}"));
                }
            }
        }
    }
    if s.version() != mutations as u64 {
        return Check::fail(ID, LABEL, format!("version {} ≠ {} real mutations", s.version(), mutations));
    }
    Check::pass(ID, LABEL, "2000 ops, model-exact")
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_basics(),
        check_cas_semantics(),
        check_versions(),
        check_retry_safety(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "kv-store", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
