//! linearizable-kv — forge lab 06 (byzantine). The capstone lab.
//!
//! A replicated log is not a database until clients can READ it without
//! being lied to. Bring your lab-05 Raft forward and turn it into a
//! linearizable key-value store: writes commit through the log, reads
//! answer ONLY from committed state — never from a leader's hopeful,
//! uncommitted tail.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/raft.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The command language (entries in your log):
//!   * `put k v`       — set key k to value v
//!   * `cas k old new` — compare-and-swap: set k = new ONLY IF the current
//!                       committed value of k is `old`. Evaluated AT APPLY
//!                       TIME against committed state (an absent key never
//!                       matches). This is what makes concurrent clients
//!                       safe: two cas k 1 2 and cas k 1 3 — exactly one wins.
//!
//! Add to your lab-05 code:
//!   * `get(key) -> Option<String>`: a LINEARIZABLE read. Replay the
//!     committed prefix of your full logical history (snapshot commands,
//!     then live entries up to commit_index), applying puts and
//!     (conditionally) casses in order, and answer from that. If it isn't
//!     committed, it doesn't exist — a partitioned leader that accepted a
//!     write it can't replicate must NOT return it.
//!
//! The judges replay your committed log themselves and compare: your
//! `get` on EVERY node must equal the replay, after partition churn.

mod raft;

use raft::{Msg, Raft, Role};
use kslab::{Check, Report};
use std::collections::HashMap;

pub const N: usize = 5;
const HB_TICKS: u32 = 6;
const COMPACT_AT: usize = 24;
const COMPACT_TO: u64 = 12;

#[derive(Clone)]
struct Envelope {
    from: usize,
    to: usize,
    msg: Msg,
    deliver_at: u32,
}

struct Net {
    tick: u32,
    in_flight: Vec<Envelope>,
    partition: Option<(Vec<usize>, Vec<usize>)>,
    loss_pct: u32,
    rng: u64,
}

impl Net {
    fn new(loss_pct: u32) -> Self {
        Net { tick: 0, in_flight: Vec::new(), partition: None, loss_pct, rng: 0x5AA5 }
    }
    fn rand(&mut self) -> u64 {
        let mut x = self.rng;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.rng = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn deliverable(&self, from: usize, to: usize) -> bool {
        if let Some((a, b)) = &self.partition {
            let ina = |x: usize| a.contains(&x);
            let inb = |x: usize| b.contains(&x);
            if (ina(from) && inb(to)) || (inb(from) && ina(to)) {
                return false;
            }
        }
        true
    }
}

fn queue_broadcast(net: &mut Net, from: usize, msgs: Vec<Msg>) {
    for msg in msgs {
        for to in 0..N {
            if to == from {
                continue;
            }
            if net.rand() % 100 < net.loss_pct as u64 {
                continue;
            }
            let delay = (net.rand() % 3) as u32;
            net.in_flight.push(Envelope { from, to, msg: msg.clone(), deliver_at: net.tick + delay });
        }
    }
}

struct Driver {
    net: Net,
    nodes: Vec<Raft>,
    silent: Vec<u32>,
    streams: Vec<u64>,
}

impl Driver {
    fn new(loss_pct: u32) -> Self {
        Driver {
            net: Net::new(loss_pct),
            nodes: (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect(),
            silent: vec![0; N],
            streams: (0..N).map(|i| 0x9E37_5AFE + i as u64 * 0x1_2345_6789).collect(),
        }
    }
    fn leader(&self) -> Option<usize> {
        self.nodes.iter().position(|n| n.role() == Role::Leader)
    }
    fn step(&mut self) {
        self.net.tick += 1;
        let t = self.net.tick;
        if t % HB_TICKS == 0 {
            for i in 0..N {
                if self.nodes[i].role() == Role::Leader {
                    let out = self.nodes[i].heartbeat();
                    queue_broadcast(&mut self.net, i, out);
                }
            }
        }
        for i in 0..N {
            // leaders don't run election timers — they're not waiting for a heartbeat
            if self.nodes[i].role() == Role::Leader {
                continue;
            }
            self.silent[i] += 1;
            let mut x = self.streams[i];
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            self.streams[i] = x;
            let timeout = 12 + (x.wrapping_mul(0x2545_F491_4F6C_DD1D) % 14) as u32;
            if self.silent[i] >= timeout {
                self.silent[i] = 0;
                let out = self.nodes[i].on_timeout();
                queue_broadcast(&mut self.net, i, out);
            }
        }
        let arrivals: Vec<Envelope> = std::mem::take(&mut self.net.in_flight);
        let mut still = Vec::new();
        for env in arrivals {
            if env.deliver_at > t {
                still.push(env);
                continue;
            }
            if !self.net.deliverable(env.from, env.to) {
                continue;
            }
            let resets = matches!(&env.msg, Msg::AppendEntries { term, .. } if *term >= self.nodes[env.to].term());
            let out = self.nodes[env.to].on_msg(env.from as u32, env.msg);
            if resets {
                self.silent[env.to] = 0;
            }
            queue_broadcast(&mut self.net, env.to, out);
        }
        self.net.in_flight.append(&mut still);
    }
    fn drive(&mut self, ticks: u32) {
        for _ in 0..ticks {
            self.step();
            // compaction cadence: any leader with a long log compacts
            if let Some(l) = self.leader() {
                if self.nodes[l].log_len() > COMPACT_AT {
                    let out = self.nodes[l].compact(COMPACT_TO);
                    queue_broadcast(&mut self.net, l, out);
                }
            }
        }
    }
    /// propose to whatever leader we find first — may be a stale,
    /// minority leader during a partition (that's the point of one check)
    fn propose(&mut self, cmd: &str) -> bool {
        let Some(l) = self.leader() else { return false };
        self.propose_to(l, cmd)
    }
    /// propose to a SPECIFIC node (used to hand a write to a stale leader)
    fn propose_to(&mut self, i: usize, cmd: &str) -> bool {
        if self.nodes[i].role() != Role::Leader {
            return false;
        }
        let out = self.nodes[i].propose(cmd.to_string());
        queue_broadcast(&mut self.net, i, out);
        true
    }
    fn put(&mut self, k: &str, v: &str) -> bool {
        self.propose(&format!("put {k} {v}"))
    }
    fn cas(&mut self, k: &str, old: &str, new: &str) -> bool {
        self.propose(&format!("cas {k} {old} {new}"))
    }
    fn committed_logs(&self) -> Vec<Vec<String>> {
        self.nodes.iter().map(|n| n.log().into_iter().take(n.commit_index() as usize).collect()).collect()
    }
    /// the ground truth: replay a committed command prefix into KV state
    fn replay(log: &[String]) -> HashMap<String, String> {
        let mut state = HashMap::new();
        for cmd in log {
            let parts: Vec<&str> = cmd.split_whitespace().collect();
            match parts.as_slice() {
                ["put", k, v] => {
                    state.insert(k.to_string(), v.to_string());
                }
                ["cas", k, old, new] => {
                    if state.get(*k).map(String::as_str) == Some(*old) {
                        state.insert(k.to_string(), new.to_string());
                    }
                }
                _ => {}
            }
        }
        state
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. put_get_basic: writes through the log become readable everywhere —
///    every node's get() equals the replay of its committed prefix.
pub fn check_put_get_basic() -> Check {
    const ID: &str = "put_get_basic";
    const LABEL: &str = "committed writes are readable on every node";
    let mut d = Driver::new(0);
    d.drive(40);
    d.put("alpha", "1");
    d.put("beta", "2");
    d.drive(30);
    d.put("alpha", "3");
    d.drive(60);
    let logs = d.committed_logs();
    let reference = logs[0].clone();
    if reference.is_empty() {
        return Check::fail(ID, LABEL, "nothing committed");
    }
    for (i, l) in logs.iter().enumerate() {
        if *l != reference {
            return Check::fail(ID, LABEL, format!("node {i} committed prefix diverged: {} vs {} entries", l.len(), reference.len()));
        }
    }
    let truth = Driver::replay(&reference);
    for (i, n) in d.nodes.iter().enumerate() {
        for (k, v) in &truth {
            match n.get(k).as_deref() {
                Some(got) if got == v => {}
                other => return Check::fail(ID, LABEL, format!("node {i}: get({k}) = {other:?}, committed state says {v:?}")),
            }
        }
    }
    if truth.get("alpha").map(String::as_str) != Some("3") {
        return Check::fail(ID, LABEL, "committed log lost the latest put — harness bug or lost commit".to_string());
    }
    Check::pass(ID, LABEL, "every node reads exactly its committed state")
}

/// 2. cas_correctness: compare-and-swap is evaluated at apply time —
///    exactly the cas ops whose precondition holds take effect.
pub fn check_cas_correctness() -> Check {
    const ID: &str = "cas_correctness";
    const LABEL: &str = "cas applies iff committed value matches; exactly one winner";
    let mut d = Driver::new(0);
    d.drive(40);
    d.put("k", "1");
    d.drive(20);
    d.cas("k", "1", "2"); // wins
    d.cas("k", "1", "9"); // loses (value is now 2)
    d.cas("k", "2", "3"); // wins
    d.cas("ghost", "0", "1"); // loses (absent key never matches)
    d.drive(60);
    let Some(l) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader");
    };
    match d.nodes[l].get("k").as_deref() {
        Some("3") => {}
        other => return Check::fail(ID, LABEL, format!("get(k) = {other:?}, expected Some(\"3\") — cas preconditions not honored")),
    }
    if d.nodes[l].get("ghost").is_some() {
        return Check::fail(ID, LABEL, "cas on an absent key created a value — absent never matches");
    }
    let logs = d.committed_logs();
    let truth = Driver::replay(&logs[l]);
    if truth.get("k").map(String::as_str) != Some("3") || truth.contains_key("ghost") {
        return Check::fail(ID, LABEL, "harness replay disagrees — the committed log itself is wrong");
    }
    Check::pass(ID, LABEL, "cas chain resolved sequentially: k=3, ghost absent")
}

/// 3. stale_leader_fence: a minority-partitioned leader accepts a write it
///    can never commit — its get() must not return it. Reads are committed
///    state or they are fiction.
pub fn check_stale_leader_fence() -> Check {
    const ID: &str = "stale_leader_fence";
    const LABEL: &str = "stale leader never reads back an uncommitted write";
    let mut d = Driver::new(0);
    d.drive(40);
    let Some(old_leader) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    };
    d.put("k", "committed");
    d.drive(30);
    // isolate the leader with ONE follower; the other three form a majority
    let minority = vec![old_leader, (old_leader + 1) % N];
    let majority: Vec<usize> = (0..N).filter(|i| !minority.contains(i)).collect();
    d.net.partition = Some((minority.clone(), majority.clone()));
    d.drive(60); // majority side elects a fresh leader
    // the stale leader takes a write it can never replicate to a majority
    d.propose_to(old_leader, "put k phantom");
    d.drive(30);
    let got = d.nodes[old_leader].get("k");
    if got.as_deref() == Some("phantom") {
        return Check::fail(ID, LABEL, "stale leader reads its own uncommitted tail — that read is a lie");
    }
    // the majority side writes the REAL next value
    let real_leader = majority.iter().copied().find(|&i| d.nodes[i].role() == Role::Leader);
    let Some(rl) = real_leader else {
        return Check::fail(ID, LABEL, "majority side never elected a leader");
    };
    d.propose_to(rl, "put k real");
    d.drive(40);
    d.net.partition = None;
    d.drive(80);
    let logs = d.committed_logs();
    let reference = logs[rl].clone();
    for (i, l) in logs.iter().enumerate() {
        if *l != reference {
            return Check::fail(ID, LABEL, format!("node {i} diverged after heal: {} vs {} committed", l.len(), reference.len()));
        }
    }
    for (i, n) in d.nodes.iter().enumerate() {
        if n.get("k").as_deref() != Some("real") {
            return Check::fail(ID, LABEL, format!("node {i}: get(k) = {:?} after heal, expected Some(\"real\")", n.get("k")));
        }
    }
    Check::pass(ID, LABEL, "phantom write stayed invisible; healed cluster reads the real value")
}

/// 4. linearizable_storm: put/cas mix under 15% loss, a mid-run partition,
///    and compaction. Final state on EVERY node equals the replay of the
///    (identical) committed prefix. That IS linearizability.
pub fn check_linearizable_storm() -> Check {
    const ID: &str = "linearizable_storm";
    const LABEL: &str = "partition churn + compaction: reads == committed replay everywhere";
    let mut d = Driver::new(15);
    d.drive(50);
    let keys = ["a", "b", "c", "d", "e", "f"];
    for i in 0..36 {
        let k = keys[i % keys.len()];
        if i % 3 == 2 {
            d.cas(k, &format!("{}", i.saturating_sub(1)), &format!("{i}"));
        } else {
            d.put(k, &format!("{i}"));
        }
        d.drive(6);
        if i == 17 {
            d.net.partition = Some((vec![0, 1], vec![2, 3, 4]));
        }
        if i == 26 {
            d.net.partition = None;
            d.drive(30); // let one leader emerge before resuming
        }
    }
    d.drive(160);
    let logs = d.committed_logs();
    let reference = logs[0].clone();
    for (i, l) in logs.iter().enumerate() {
        if *l != reference {
            return Check::fail(ID, LABEL, format!("node {i} diverged: {} entries vs {}", l.len(), reference.len()));
        }
    }
    if reference.len() < 24 {
        return Check::fail(ID, LABEL, format!("only {} committed — convergence stalled", reference.len()));
    }
    let truth = Driver::replay(&reference);
    for (i, n) in d.nodes.iter().enumerate() {
        for k in keys {
            let want = truth.get(k).cloned();
            if n.get(k) != want {
                return Check::fail(ID, LABEL, format!("node {i}: get({k}) = {:?}, committed replay says {:?}", n.get(k), want));
            }
        }
    }
    Check::pass(ID, LABEL, format!("{} committed entries; get() == committed replay on all 5 nodes", reference.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_put_get_basic(),
        check_cas_correctness(),
        check_stale_leader_fence(),
        check_linearizable_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "linearizable-kv", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
