//! snapshots — forge lab 05 (byzantine).
//!
//! Logs can't grow forever. Bring your lab-04 Raft forward and add
//! compaction: the leader snapshots committed state, truncates the log,
//! and pulls lagging followers forward with InstallSnapshot instead of
//! a log walk back to the stone age.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/raft.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! Add to your lab-04 code:
//!   * `compact(cut)` (leader): snapshot the first `cut` committed
//!     entries (their COMMANDS are the snapshot data here — our state
//!     machine is replayable), truncate the log, remember
//!     last_included_index/term.
//!   * Heartbeats/proposals now start at last_included_index — a
//!     follower whose log ends BEFORE that point can't match: on a
//!     failed match, send InstallSnapshot { last_included_*,
//!     data: snapshot commands }.
//!   * Followers on InstallSnapshot: adopt the snapshot as committed
//!     history (commit_index = last_included_index), drop any log it
//!     covers, keep any entries BEYOND it that still match.
//!   * `log()` returns the FULL logical history: snapshot commands,
//!     then live entries. The judges compare committed prefixes.

mod raft;

use raft::{Msg, Raft, Role};
use kslab::{Check, Report};

pub const N: usize = 5;
const HB_TICKS: u32 = 6;
const COMPACT_AT: usize = 24;
const COMPACT_TO: u64 = 12;

#[derive(Clone)]
struct Envelope {
    from: usize,
    to: usize,
    msg: Msg,
    deliver_at: u32,
}

struct Net {
    tick: u32,
    in_flight: Vec<Envelope>,
    partition: Option<(Vec<usize>, Vec<usize>)>,
    loss_pct: u32,
    rng: u64,
}

impl Net {
    fn new(loss_pct: u32) -> Self {
        Net { tick: 0, in_flight: Vec::new(), partition: None, loss_pct, rng: 0x5AA5 }
    }
    fn rand(&mut self) -> u64 {
        let mut x = self.rng;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.rng = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn deliverable(&self, from: usize, to: usize) -> bool {
        if let Some((a, b)) = &self.partition {
            let ina = |x: usize| a.contains(&x);
            let inb = |x: usize| b.contains(&x);
            if (ina(from) && inb(to)) || (inb(from) && ina(to)) {
                return false;
            }
        }
        true
    }
}

fn queue_broadcast(net: &mut Net, from: usize, msgs: Vec<Msg>) {
    for msg in msgs {
        for to in 0..N {
            if to == from {
                continue;
            }
            if net.rand() % 100 < net.loss_pct as u64 {
                continue;
            }
            let delay = (net.rand() % 3) as u32;
            net.in_flight.push(Envelope { from, to, msg: msg.clone(), deliver_at: net.tick + delay });
        }
    }
}

struct Driver {
    net: Net,
    nodes: Vec<Raft>,
    silent: Vec<u32>,
    streams: Vec<u64>,
}

impl Driver {
    fn new(loss_pct: u32) -> Self {
        Driver {
            net: Net::new(loss_pct),
            nodes: (0..N).map(|i| Raft::new(i as u32, (0..N as u32).filter(|&p| p as usize != i).collect())).collect(),
            silent: vec![0; N],
            streams: (0..N).map(|i| 0x9E37_5AFE + i as u64 * 0x1_2345_6789).collect(),
        }
    }
    fn leader(&self) -> Option<usize> {
        self.nodes.iter().position(|n| n.role() == Role::Leader)
    }
    fn step(&mut self) {
        self.net.tick += 1;
        let t = self.net.tick;
        if t % HB_TICKS == 0 {
            for i in 0..N {
                if self.nodes[i].role() == Role::Leader {
                    let out = self.nodes[i].heartbeat();
                    queue_broadcast(&mut self.net, i, out);
                }
            }
        }
        for i in 0..N {
            // leaders don't run election timers — they're not waiting for a heartbeat
            if self.nodes[i].role() == Role::Leader {
                continue;
            }
            self.silent[i] += 1;
            let mut x = self.streams[i];
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            self.streams[i] = x;
            let timeout = 12 + (x.wrapping_mul(0x2545_F491_4F6C_DD1D) % 14) as u32;
            if self.silent[i] >= timeout {
                self.silent[i] = 0;
                let out = self.nodes[i].on_timeout();
                queue_broadcast(&mut self.net, i, out);
            }
        }
        let arrivals: Vec<Envelope> = std::mem::take(&mut self.net.in_flight);
        let mut still = Vec::new();
        for env in arrivals {
            if env.deliver_at > t {
                still.push(env);
                continue;
            }
            if !self.net.deliverable(env.from, env.to) {
                continue;
            }
            let resets = matches!(&env.msg, Msg::AppendEntries { term, .. } if *term >= self.nodes[env.to].term());
            let out = self.nodes[env.to].on_msg(env.from as u32, env.msg);
            if resets {
                self.silent[env.to] = 0;
            }
            queue_broadcast(&mut self.net, env.to, out);
        }
        self.net.in_flight.append(&mut still);
    }
    fn drive(&mut self, ticks: u32) {
        for _ in 0..ticks {
            self.step();
            // compaction cadence: any leader with a long log compacts
            if let Some(l) = self.leader() {
                if self.nodes[l].log_len() > COMPACT_AT {
                    let out = self.nodes[l].compact(COMPACT_TO);
                    queue_broadcast(&mut self.net, l, out);
                }
            }
        }
    }
    fn propose(&mut self, cmd: &str) -> bool {
        let Some(l) = self.leader() else { return false };
        let out = self.nodes[l].propose(cmd.to_string());
        queue_broadcast(&mut self.net, l, out);
        true
    }
    fn committed_logs(&self) -> Vec<Vec<String>> {
        self.nodes.iter().map(|n| n.log().into_iter().take(n.commit_index() as usize).collect()).collect()
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. compact_bounds: after 30 writes, the leader's live log is bounded
///    and its full history (snapshot + log) is intact.
pub fn check_compact_bounds() -> Check {
    const ID: &str = "compact_bounds";
    const LABEL: &str = "log stays bounded; history intact via snapshot";
    let mut d = Driver::new(0);
    d.drive(40);
    for i in 0..30 {
        d.propose(&format!("set k{i}={i}"));
        d.drive(6);
    }
    d.drive(60);
    let Some(l) = d.leader() else {
        return Check::fail(ID, LABEL, "no leader");
    };
    let live = d.nodes[l].log_len();
    let history = d.nodes[l].log().len();
    if live > COMPACT_AT + 8 {
        return Check::fail(ID, LABEL, format!("live log is {live} entries — compaction never happened"));
    }
    if history < 30 {
        return Check::fail(ID, LABEL, format!("full history is {history} entries after 30 writes — snapshot lost commands"));
    }
    Check::pass(ID, LABEL, format!("live log {live}, full history {history} — compacted correctly"))
}

/// 2. snapshot_catchup: a node partitioned past the truncation point
///    catches up via InstallSnapshot after healing.
pub fn check_snapshot_catchup() -> Check {
    const ID: &str = "snapshot_catchup";
    const LABEL: &str = "lagging node catches up via snapshot, not log walk";
    let mut d = Driver::new(0);
    d.drive(40);
    if d.leader().is_none() {
        return Check::fail(ID, LABEL, "no leader in phase 1");
    }
    d.propose("set seed=1");
    d.drive(30);
    // isolate node 4; write 30 entries (compaction will truncate them)
    d.net.partition = Some((vec![4], vec![0, 1, 2, 3]));
    for i in 0..30 {
        d.propose(&format!("set x{i}={i}"));
        d.drive(6);
    }
    d.drive(40);
    // heal and converge
    d.net.partition = None;
    d.drive(100);
    let logs = d.committed_logs();
    let reference = logs[0].clone();
    if logs[4] != reference {
        return Check::fail(ID, LABEL, format!("node 4 never converged: {} committed entries vs {} elsewhere", logs[4].len(), reference.len()));
    }
    if !reference.contains(&"set x29=29".to_string()) {
        return Check::fail(ID, LABEL, "majority history incomplete after heal");
    }
    Check::pass(ID, LABEL, "node 4 rejoined whole — snapshot carried it over the gap")
}

/// 3. state_after_compact: committed state is queryable after compaction
///    (the snapshot IS the state, not a hole in it).
pub fn check_state_after_compact() -> Check {
    const ID: &str = "state_after_compact";
    const LABEL: &str = "early commands remain in committed history after compaction";
    let mut d = Driver::new(0);
    d.drive(40);
    d.propose("set early=1");
    d.drive(30);
    for i in 0..28 {
        d.propose(&format!("set f{i}={i}"));
        d.drive(6);
    }
    d.drive(80);
    let logs = d.committed_logs();
    if !logs[0].contains(&"set early=1".to_string()) {
        return Check::fail(ID, LABEL, "the earliest committed command vanished into the snapshot — history must include it");
    }
    Check::pass(ID, LABEL, "snapshot + live log = one continuous history")
}

/// 4. storm_compact: 40 writes, 15% loss, compaction on — identical
///    committed prefixes on all nodes.
pub fn check_storm_compact() -> Check {
    const ID: &str = "storm_compact";
    const LABEL: &str = "40 writes under loss + compaction: one history everywhere";
    let mut d = Driver::new(15);
    d.drive(50);
    for i in 0..40 {
        d.propose(&format!("set s{i}={i}"));
        d.drive(7);
    }
    d.drive(160);
    let logs = d.committed_logs();
    let reference = logs[0].clone();
    for (i, l) in logs.iter().enumerate() {
        if *l != reference {
            return Check::fail(ID, LABEL, format!("node {i} diverged: {} entries vs {}", l.len(), reference.len()));
        }
    }
    if reference.len() < 25 {
        return Check::fail(ID, LABEL, format!("only {} committed — convergence stalled", reference.len()));
    }
    Check::pass(ID, LABEL, format!("{} committed entries, identical on all nodes", reference.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_compact_bounds(),
        check_snapshot_catchup(),
        check_state_after_compact(),
        check_storm_compact(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "snapshots", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
