//! echo-node — forge lab 01 (byzantine).
//!
//! Exactly-once effects over at-least-once delivery. The harness plays the
//! network: it will lose some deliveries and duplicate others, and your
//! node must process each unique message EXACTLY once while answering
//! EVERY delivery. This is the idempotent-receiver pattern — the seed of
//! every replicated state machine in this course.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/node.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The network contract (what the harness enforces):
//!   * Every message is (from, seq, payload). seq is per-sender monotonic.
//!   * Delivery is at-least-once: each message is delivered 1+ times.
//!   * A correct node: each unique (from, seq) is PROCESSED once —
//!     `processed_count` counts unique messages — and every delivery
//!     produces a reply carrying the ORIGINAL answer for that message.
//!   * Replays must not re-execute: if (2, seq 7, "write x") already ran,
//!     a replay returns the stored reply; it does not run the write again.

mod node;

use node::Node;
use kslab::{Check, Report};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. echo_basic: the reply mirrors payload and seq, addressed to the sender.
pub fn check_echo_basic() -> Check {
    const ID: &str = "echo_basic";
    const LABEL: &str = "echo: reply mirrors payload and seq";
    let mut n = Node::new(1);
    let replies = n.on_message(2, 1, "ping");
    if replies.len() != 1 {
        return Check::fail(ID, LABEL, format!("expected exactly 1 reply, got {}", replies.len()));
    }
    let r = &replies[0];
    if r.to != 2 || r.seq != 1 || r.payload != "ping" {
        return Check::fail(ID, LABEL, format!("reply = (to:{}, seq:{}, {:?}), want (to:2, seq:1, \"ping\")", r.to, r.seq, r.payload));
    }
    Check::pass(ID, LABEL, "reply mirrors the message")
}

/// 2. dup_effect_once: three deliveries of the same message → processed
///    once, answered every time with the same payload.
pub fn check_dup_effect_once() -> Check {
    const ID: &str = "dup_effect_once";
    const LABEL: &str = "duplicates: effect once, answered every time";
    let mut n = Node::new(1);
    let mut payloads = Vec::new();
    for _ in 0..3 {
        let replies = n.on_message(2, 7, "write x=1");
        if replies.len() != 1 {
            return Check::fail(ID, LABEL, "every delivery must be answered — at-least-once answering is the contract");
        }
        payloads.push(replies[0].payload.clone());
    }
    if n.processed_count() != 1 {
        return Check::fail(ID, LABEL, format!("processed_count = {}, want 1 — the effect ran more than once", n.processed_count()));
    }
    if payloads.iter().any(|p| p != "write x=1") {
        return Check::fail(ID, LABEL, "replays returned different answers — store and return the ORIGINAL reply");
    }
    Check::pass(ID, LABEL, "1 effect, 3 identical answers")
}

/// 3. monotonic_seq: replays of an old seq after newer ones return the
///    original answer (response caching, not recomputation).
pub fn check_monotonic_seq() -> Check {
    const ID: &str = "monotonic_seq";
    const LABEL: &str = "replayed seq returns the original answer";
    let mut n = Node::new(1);
    n.on_message(9, 1, "a");
    n.on_message(9, 2, "b");
    n.on_message(9, 3, "c");
    let replay = n.on_message(9, 2, "b");
    if replay.len() != 1 || replay[0].payload != "b" {
        return Check::fail(ID, LABEL, format!("replay of seq 2 returned {:?}, want the original \"b\"", replay.first().map(|r| &r.payload)));
    }
    if n.processed_count() != 3 {
        return Check::fail(ID, LABEL, format!("processed_count = {}, want 3 — the replay was re-executed", n.processed_count()));
    }
    Check::pass(ID, LABEL, "the table remembers answers, not just presence")
}

/// 4. multi_sender: dedup keys are (sender, seq) — sender 3's seq 1 is NOT
///    a replay of sender 2's seq 1.
pub fn check_multi_sender() -> Check {
    const ID: &str = "multi_sender";
    const LABEL: &str = "dedup is per (sender, seq), not global";
    let mut n = Node::new(1);
    n.on_message(2, 1, "from-two");
    let r = n.on_message(3, 1, "from-three");
    if r.len() != 1 || r[0].payload != "from-three" {
        return Check::fail(ID, LABEL, "sender 3's seq 1 was treated as a replay of sender 2's seq 1 — key on (sender, seq)");
    }
    if n.processed_count() != 2 {
        return Check::fail(ID, LABEL, format!("processed_count = {}, want 2", n.processed_count()));
    }
    Check::pass(ID, LABEL, "per-sender dedup works")
}

/// 5. storm: 2000 deliveries, 8 senders, ~30% replays — every unique
///    message processed exactly once, every delivery answered.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "2000 hostile deliveries: exactly-once effects";
    let mut n = Node::new(1);
    let mut rng = Rng(0x5701);
    // each sender emits seqs 1..=25; the network delivers each 1..4 times in shuffled order
    let mut unique: Vec<(u32, u64, String)> = Vec::new();
    for from in 2..10u32 {
        for seq in 1..=25u64 {
            unique.push((from, seq, format!("m{from}-{seq}")));
        }
    }
    let mut deliveries = Vec::new();
    for (from, seq, payload) in &unique {
        let times = 1 + rng.below(3);
        for _ in 0..times {
            deliveries.push((*from, *seq, payload.clone()));
        }
    }
    // shuffle deterministically
    for i in (1..deliveries.len()).rev() {
        let j = rng.below(i + 1);
        deliveries.swap(i, j);
    }
    for (from, seq, payload) in &deliveries {
        let replies = n.on_message(*from, *seq, payload);
        if replies.len() != 1 || replies[0].payload != *payload {
            return Check::fail(ID, LABEL, format!("delivery ({from}, {seq}) answered wrongly"));
        }
    }
    let want = unique.len();
    let got = n.processed_count();
    if got != want {
        return Check::fail(ID, LABEL, format!("processed_count = {got}, want {want} — duplicates leaked through as new effects"));
    }
    Check::pass(ID, LABEL, format!("{} deliveries, {want} unique effects, zero leakage", deliveries.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_echo_basic(),
        check_dup_effect_once(),
        check_monotonic_seq(),
        check_multi_sender(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "echo-node", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
